modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "CC0"

[[mods]]
modId = "imlocalizer"
version = "${version}"
displayName = "IMLocalizer"
authors = "TexTrue"
description = '''

'''
#logoFile = ""

[[dependencies.imlocalizer]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.imlocalizer]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"
